default_profile = "generate-inv"

[profiles.generate-inv]
adapter = "sqlite"
conn_str = [ "/Users/kb/.local/share/generate-inv/generate-inv.db" ]
keymap_name = [ "vscode" ]
limit = 100000
theme = "nord"
